[package]
name = "isort"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["x48 <x48@x48.org>"]

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
rayon = "1.11.0"
